name: Build Flutter APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         submodules: true

  #     - name: Debug - List root
  #       run: ls -la

  #     - name: Debug - List simple_live_app
  #       run: ls -la ./simple_live_app

  #     - name: Set up Flutter (3.22.0)
  #       uses: subosito/flutter-action@v2
  #       with:
  #         channel: 'stable'
  #         flutter-version: '3.22.0'

  #     - name: Install dependencies
  #       run: flutter pub get
  #       working-directory: ./simple_live_app

  #     - name: Patch Android to use debug signing for release
  #       run: |
  #         sed -i 's/signingConfig signingConfigs.release/signingConfig signingConfigs.debug/g' android/app/build.gradle
  #       working-directory: ./simple_live_app

  #     - name: Build APK (Release)
  #       run: flutter build apk --release --no-shrink
  #       working-directory: ./simple_live_app

  #     - name: Upload APK Artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: app-release
  #         path: simple_live_app/build/app/outputs/flutter-apk/app-release.apk
          
  # 打包Windows
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      # 签出代码
      - uses: actions/checkout@v4
        # with:
          # ref: dev
      # 设置Flutter环境
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.x"
          cache: true
      - name: Enable Flutter Desktop
        run: flutter config --enable-windows-desktop
      - name: Restore Packages
        run: |
          cd simple_live_app
          flutter pub get
      # 设置flutter_distributor环境
      - name: Install flutter_distributor
        run: dart pub global activate flutter_distributor
      # build Windows ZIP\MSIX
      - name: Build Windows
        run: |
          cd simple_live_app
          flutter_distributor package --platform windows --targets msix,zip --skip-clean
      # 上传Windows至Artifacts
      - name: Upload Windows APP to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: |
            simple_live_app/build/dist/*/*.msix
            simple_live_app/build/dist/*/*.zip
        #完成
      - run: echo "🍏 Windows job's status is ${{ job.status }}."
